### ISSUE TITLE
A word from the author

### ISSUE THREAD

**Issue by naryl** [lisp-mirror/cl-tui#1]
Hello. I wrote cl-tui's initial version and I may need it again. So, thanks for keeping it safe on github. :) I wanted to say a few things completely unrelated to each other:
1. The point of not exporting `frame` is that you're not supposed to use that symbol in user code. Frames are only created with `define-frame`. There are six examples in the examples directory and none of them use the `frame` symbol.
2. Are there any major new features in cl-charms since six years ago that cl-tui may use? :)
3. What happened to `cl-charms:ok`? Loading `cl-tui` fails because it's not there anymore.
4. I'd like to update it to work on modern `cl-charms` and add a few features. And actually use in a real app this time. Can I get write permissions to this repo or should I fork or continue on bitbucket?

**Comment by naryl** [comment]
Ok, I'll answer 2 and 3 myself.
2. The high-level API.
3. It moved to `charms/ll`, with all the other functions I used.
So, only 1 and 4 remain.

**Comment by naryl** [comment]
I'll answer 1 too. There's no reason to export `frame` but I actually accepted the commit on bitbucket six years ago...
Anyway, the updated code to use `charms/ll` and something else to make all the tests run is on bitbucket. Let's get 4 done.

**Comment by naryl** [comment]
... I messed up cl-charms and cl-tui repos. I thought I'm talking to HiTECNOLOGYs this whole time.

So, how should we go about continuing cl-tui development?

**Comment by vindarel** [comment]
Hello^^ I suggest we do not use this repo for development. You could carry on on Bitbucket or re-publish everything on Github? (this repo should not be seen as the original one of your fork, that makes no sense).

I'm glad to see development starting again :)

**Comment by naryl** [comment]
I strongly prefer Mercurial, which is why I used Bitbucket in the first place. If I want to keep it on Mercurial I'll have to use Source Forge which is fine with me but may make maintaining the mirror a hassle. E.g. wxCL is a project originally on Source Forge and mirrored here.

If maintaining a mirror from SourceForge like wxCL is too much hassle for you then I'll just republish it and continue here on Github.

**Comment by vindarel** [comment]
Do the simplest for you (but +1 for Github over SourceForge). 

I can of course make you the owner of this, or transfer it to you. Or, just ignore this repo and make your own.

**Comment by naryl** [comment]
I forgot you can transfer the repo to me. Let's do it this way.

**Comment by vindarel** [comment]
arf, I can't

>  You can only transfer a repository from an organization to yourself at this time 

this + I have to stop the mirroring on my server,… it's simpler for you to clone it and push it to a new repo no?

**Comment by naryl** [comment]
Ok, change the mirroring to this repo: http://hg.code.sf.net/p/cl-tui/code

**Comment by naryl** [comment]
Alright, visibility is more important (it may be useful for lots of people) so I'll put this project on github.

https://github.com/naryl/cl-tui

**Comment by vindarel** [comment]
Cool! I copied this new url to this mirror's header.
